### ISSUE TITLE
Incompatibility with latest version of Networkx

### ISSUE THREAD

**Issue by taynaud** [taynaud/python-louvain#3]
networkx==2.0 implements G.edges() instead of G.edges_iter(). When would you provide a version with updated best_partition() code that will be compatible with that change?

File "/usr/local/lib/python2.7/site-packages/community/community_louvain.py", line 203, in best_partition dendo = generate_dendrogram(graph, partition, weight, resolution) File "/usr/local/lib/python2.7/site-packages/community/community_louvain.py", line 285, in generate_dendrogram current_graph = induced_graph(partition, current_graph, weight) File "/usr/local/lib/python2.7/site-packages/community/community_louvain.py", line 339, in induced_graph for node1, node2, datas in graph.edges_iter(data=True): AttributeError: 'Graph' object has no attribute 'edges_iter'

**Comment by DinosC** [comment]
Hi, is there any update? I am experiencing the same problem. Thanks

**Comment by taynaud** [comment]
Hi, latest master is now compatible. I have not done extensive testing though, so be carefull with your results.

I'll make a release after networkx 2.0 release, but you can already install it with

`pip install -U git+https://github.com/taynaud/python-louvain.git`

Best

**Comment by DinosC** [comment]
Hi, thanks a lot for the reply. I ll try your guideline. For now I
installed 1.11 version to work

Best

2017-02-22 10:14 GMT+01:00 Thomas Aynaud <notifications@github.com>:

**Comment by taynaud** [comment]
Work for networkx 2 is now in separate branch. Install with

`pip install -U git+https://github.com/taynaud/python-louvain.git@networkx2`

**Comment by taynaud** [comment]
version 0.9 handles networkx 2.0

**Comment by ColinWilder** [comment]
Had same problem, in code for doing SNA at https://programminghistorian.org/lessons/exploring-and-analyzing-network-data-with-python. @taynaud's code
`pip install -U git+https://github.com/taynaud/python-louvain.git`
worked for me.

**Comment by taynaud** [comment]
Hello, 

`pip install -U python-louvain` should upgrade to 0.9 which works well with networkx 2.0.

You have issue with this version and networkx 2.0 ?

Best

**Comment by zikoalexis** [comment]
Heloo @taynaud  I still have the same problem even if i have the version netwrokx=2.0 ?? Can you please help me ?

**Comment by taynaud** [comment]
Hello, 

If you use networkx>=2.0, you need to use python-louvain>0.8 (latest is best)

If you use networkx<2.0, you need to use python-louvain==0.8

So, my advice is to use the maximal networkx version compatible with your code/dependencies and then select the python-louvain version depending on this choice.

I will add version information inside the package to allow to insure the used version, it is often difficult to now what you are using, depending on the virtual env, system... It will be tracked with https://github.com/taynaud/python-louvain/issues/20

**Comment by zikoalexis** [comment]
Thank you Taynaud i used the version networkx >2 and the python-louvain And it worked very well for me !!

**Comment by snehalkatre** [comment]
Hi - I have networkx 2.2 and python-louvain version 0.11 and I still get this error

**Comment by snehalkatre** [comment]
I seem to have the correction versions: 
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:21:59) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import community
>>> community.__version__
'0.11'
>>> import networkx
>>> networkx.__version__
'2.2'

**Comment by taynaud** [comment]
Can you give me a code snippet which trigger the error ? And maybe your stack trace ?

Thanks

**Comment by taynaud** [comment]
You can also try to update the module (`pip install -U python-louvain`), it should say 0.13 now

**Comment by leonardorocc0** [comment]
same error in here:
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import community
>>> community.__version__
'0.13'
>>> import networkx
>>> networkx.__version__
'2.2'
```
the error I get is:
partition = community.best_partition(G)

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-ed8b62e88c8f> in <module>()
      1 #first compute the best partition
----> 2 partition = community.best_partition(G)
      3 # Find modularity
      4 mod = community.modularity(partition,G)
      5 # print (G.number_of_edges)

~/anaconda3/lib/python3.6/site-packages/community/community_louvain.py in best_partition(graph, partition, weight, resolution)
    201     Raises
    202     ------
--> 203     NetworkXError
    204        If the graph is not Eulerian.
    205 

~/anaconda3/lib/python3.6/site-packages/community/community_louvain.py in generate_dendrogram(graph, part_init, weight, resolution)
    283     -------
    284     dendrogram : list of dictionaries
--> 285         a list of partitions, ie dictionnaries where keys of the i+1 are the
    286         values of the i. and where keys of the first are the nodes of graph
    287 

~/anaconda3/lib/python3.6/site-packages/community/community_louvain.py in induced_graph(partition, graph, weight)
    337     if graph.number_of_edges() == 0:
    338         part = dict([])
--> 339         for i, node in enumerate(graph.nodes()):
    340             part[node] = i
    341         return [part]

AttributeError: 'Graph' object has no attribute 'edges_iter'
```

Thank you

**Comment by Cherishsword** [comment]
install with 
`pip install -U git+https://github.com/taynaud/python-louvain.git` or ‘pip install -U git+https://github.com/taynaud/python-louvain.git@networkx2’
have same problem
`AttributeError                            Traceback (most recent call last)
<ipython-input-124-6c9f6a4cbb32> in <module>()
      1 import community                                    # python-louvain
----> 2 partition = community.best_partition(G_main)         # Louvain算法划分社区
      3 comm_dict = defaultdict(list)
      4 for person in partition:
      5     comm_dict[partition[person]].append(person)

d:\安装程序\python36\lib\site-packages\python_louvain-0.4-py3.6.egg\community\community_louvain.py in best_partition(graph, partition, weight, resolution)
    201     >>> plt.show()
    202     """
--> 203     dendo = generate_dendrogram(graph, partition, weight, resolution)
    204     return partition_at_level(dendo, len(dendo) - 1)
    205 

d:\安装程序\python36\lib\site-packages\python_louvain-0.4-py3.6.egg\community\community_louvain.py in generate_dendrogram(graph, part_init, weight, resolution)
    283     status_list.append(partition)
    284     mod = new_mod
--> 285     current_graph = induced_graph(partition, current_graph, weight)
    286     status.init(current_graph, weight)
    287 

d:\安装程序\python36\lib\site-packages\python_louvain-0.4-py3.6.egg\community\community_louvain.py in induced_graph(partition, graph, weight)
    337     ret.add_nodes_from(partition.values())
    338 
--> 339     for node1, node2, datas in graph.edges_iter(data=True):
    340         edge_weight = datas.get(weight, 1)
    341         com1 = partition[node1]

AttributeError: 'Graph' object has no attribute 'edges_iter'`

**Comment by leonardorocc0** [comment]
python-louvain-0.8 worked for me.
Thesis director will be happy.
Thanks @Cherishsword

**Comment by Hartry** [comment]
hiii everyone, 
I had the same error 
`AttributeError: 'MultiDiGraph' object has no attribute 'edges_iter'`

I followed your recommandation by udpating my Networkx package with the command 

`pip install -U git+https://github.com/taynaud/python-louvain.git`

but I still have the same error.. there is my complete code.. :/ 


`import osmnx as ox
 import networkx as nx


name_place = "Aubervilliers, France"
graphe_champs = ox.graph_from_address(name_place,network_type='all')
[e for e in graphe_champs.edges_iter()]


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-a0fcf017a545> in <module>
----> 1 [e for e in graphe_champs.edges_iter()]

AttributeError: 'MultiDiGraph' object has no attribute 'edges_iter'`

**Comment by aslicanibek** [comment]
Hi,
I am new to networkx and community detection.

I am using the latest versions of both networkx and python-louvain. However it seems the incompatibility issue still exist for me.

I get the error:

'Graph' object has no attribute 'edges_iter'

Any suggestions how can I solve this issue? I tried 
!pip install -U git+https://github.com/taynaud/python-louvain.git did not work.

Thanks a lot

**Comment by LauFernanda** [comment]
Hi,
I'm using Networkx 2.3 and have tried with python-louvain 0.13 and 0.8 without success. Seems that the problem persists :(
